/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class ClientClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:44306";
    }

    getClients(): Promise<ClientResponse[]> {
        let url_ = this.baseUrl + "/api/Client";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetClients(_response);
        });
    }

    protected processGetClients(response: Response): Promise<ClientResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ClientResponse.fromJS(item));
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientResponse[]>(<any>null);
    }
}

export class TimesheetClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:44306";
    }

    getTimesheets(): Promise<Timesheet[]> {
        let url_ = this.baseUrl + "/api/Timesheet";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetTimesheets(_response);
        });
    }

    protected processGetTimesheets(response: Response): Promise<Timesheet[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Timesheet.fromJS(item));
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Timesheet[]>(<any>null);
    }

    saveTimesheet(timesheet: TimesheetRequest): Promise<FileResponse | null> {
        let url_ = this.baseUrl + "/api/Timesheet";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(timesheet);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveTimesheet(_response);
        });
    }

    protected processSaveTimesheet(response: Response): Promise<FileResponse | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse | null>(<any>null);
    }
}

export class ClientResponse implements IClientResponse {
    clientId!: number;
    name?: string | undefined;

    constructor(data?: IClientResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.clientId = _data["clientId"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): ClientResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ClientResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["clientId"] = this.clientId;
        data["name"] = this.name;
        return data; 
    }
}

export interface IClientResponse {
    clientId: number;
    name?: string | undefined;
}

export class Timesheet implements ITimesheet {
    timesheetId!: number;
    date!: Date;
    timesheetRows?: TimesheetRow[] | undefined;
    employeeId!: number;

    constructor(data?: ITimesheet) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timesheetId = _data["timesheetId"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            if (Array.isArray(_data["timesheetRows"])) {
                this.timesheetRows = [] as any;
                for (let item of _data["timesheetRows"])
                    this.timesheetRows!.push(TimesheetRow.fromJS(item));
            }
            this.employeeId = _data["employeeId"];
        }
    }

    static fromJS(data: any): Timesheet {
        data = typeof data === 'object' ? data : {};
        let result = new Timesheet();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timesheetId"] = this.timesheetId;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        if (Array.isArray(this.timesheetRows)) {
            data["timesheetRows"] = [];
            for (let item of this.timesheetRows)
                data["timesheetRows"].push(item.toJSON());
        }
        data["employeeId"] = this.employeeId;
        return data; 
    }
}

export interface ITimesheet {
    timesheetId: number;
    date: Date;
    timesheetRows?: TimesheetRow[] | undefined;
    employeeId: number;
}

export class TimesheetRow implements ITimesheetRow {
    id!: number;
    date!: Date;
    clientId!: number;
    duration!: number;
    notes?: string | undefined;
    timesheetId!: number;

    constructor(data?: ITimesheetRow) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.clientId = _data["clientId"];
            this.duration = _data["duration"];
            this.notes = _data["notes"];
            this.timesheetId = _data["timesheetId"];
        }
    }

    static fromJS(data: any): TimesheetRow {
        data = typeof data === 'object' ? data : {};
        let result = new TimesheetRow();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["clientId"] = this.clientId;
        data["duration"] = this.duration;
        data["notes"] = this.notes;
        data["timesheetId"] = this.timesheetId;
        return data; 
    }
}

export interface ITimesheetRow {
    id: number;
    date: Date;
    clientId: number;
    duration: number;
    notes?: string | undefined;
    timesheetId: number;
}

export class TimesheetRequest implements ITimesheetRequest {
    date!: Date;
    employeeId!: number;
    timesheetRows?: TimesheetRowRequest[] | undefined;

    constructor(data?: ITimesheetRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.employeeId = _data["employeeId"];
            if (Array.isArray(_data["timesheetRows"])) {
                this.timesheetRows = [] as any;
                for (let item of _data["timesheetRows"])
                    this.timesheetRows!.push(TimesheetRowRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TimesheetRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TimesheetRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["employeeId"] = this.employeeId;
        if (Array.isArray(this.timesheetRows)) {
            data["timesheetRows"] = [];
            for (let item of this.timesheetRows)
                data["timesheetRows"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ITimesheetRequest {
    date: Date;
    employeeId: number;
    timesheetRows?: TimesheetRowRequest[] | undefined;
}

export class TimesheetRowRequest implements ITimesheetRowRequest {
    timesheetRowId?: number | undefined;
    date?: string | undefined;
    clientId!: number;
    clientName?: string | undefined;
    duration!: number;
    notes?: string | undefined;
    timesheetId!: number;

    constructor(data?: ITimesheetRowRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timesheetRowId = _data["timesheetRowId"];
            this.date = _data["date"];
            this.clientId = _data["clientId"];
            this.clientName = _data["clientName"];
            this.duration = _data["duration"];
            this.notes = _data["notes"];
            this.timesheetId = _data["timesheetId"];
        }
    }

    static fromJS(data: any): TimesheetRowRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TimesheetRowRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timesheetRowId"] = this.timesheetRowId;
        data["date"] = this.date;
        data["clientId"] = this.clientId;
        data["clientName"] = this.clientName;
        data["duration"] = this.duration;
        data["notes"] = this.notes;
        data["timesheetId"] = this.timesheetId;
        return data; 
    }
}

export interface ITimesheetRowRequest {
    timesheetRowId?: number | undefined;
    date?: string | undefined;
    clientId: number;
    clientName?: string | undefined;
    duration: number;
    notes?: string | undefined;
    timesheetId: number;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}